export const actionTypes = {
  //前台
  SEARCH_DATA: 'SEARCH_DATA',
  GET_SEARCH_TOTAL_DATA: 'GET_SEARCH_TOTAL_DATA',
  SEARCH_PAGE_DATA: 'SEARCH_PAGE_DATA',
  GET_LIFE:'GET_LIFE',

  POST_COMMENTS: 'POST_COMMENTS',
  POST_ARTICLE: 'POST_ARTICLE',
  //后台
  GET_ADMIN_DATA:'GET_ADMIN_DATA',
  POST_ADMIN_DETAIL:'POST_ADMIN_DETAIL',
  POST_ADMIN_PASSWORD:'POST_ADMIN_PASSWORD',
}