export const actionTypes = {
  //前台
  SEARCH_DATA: 'SEARCH_DATA',
  GET_SEARCH_TOTAL_DATA: 'GET_SEARCH_TOTAL_DATA',
  SEARCH_PAGE_DATA: 'SEARCH_PAGE_DATA',
  GET_LIFE:'GET_LIFE',
  GET_USER_COMMENT:'GET_USER_COMMENT',
  GET_COMMENTS:'GET_COMMENTS',
  GET_COMMENTS_USER:'GET_COMMENTS_USER',
  ADD_ZAN:'ADD_ZAN',
  SAVE_IP:'SAVE_IP',
  GET_IP:'GET_IP',

  POST_COMMENTS: 'POST_COMMENTS',
  POST_USER_COMMENTS: 'POST_USER_COMMENTS',
  POST_ARTICLE: 'POST_ARTICLE',
  //后台
  GET_ADMIN_DATA:'GET_ADMIN_DATA',
  POST_ADMIN_DETAIL:'POST_ADMIN_DETAIL',
  POST_ADMIN_PASSWORD:'POST_ADMIN_PASSWORD',
}