export const actionTypes = {
  //前台
  SEARCH_DATA: 'SEARCH_DATA',
  GET_SEARCH_TOTAL_DATA: 'GET_SEARCH_TOTAL_DATA',
  SEARCH_PAGE_DATA: 'SEARCH_PAGE_DATA',

  POST_COMMENTS: 'POST_COMMENTS',
  //后台
  GET_ADMIN_DATA:'GET_ADMIN_DATA'
}